import type { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Terms of Use",
  description:
    "AstraMind Terms of Use - Understand the terms and conditions for using our platform.",
};

const sections: { title: string; body: ReactNode }[] = [
  {
    title: "Acceptance",
    body: (
      <p>
        By using AstraMind you agree to these terms. If you do not agree, do not
        use the app.
      </p>
    ),
  },
  {
    title: "The service",
    body: (
      <p>
        AstraMind lets you upload PDF files (up to 10 MB each) and ask questions
        answered with the help of an AI model. It is provided as a personal
        project and may change or stop at any time.
      </p>
    ),
  },
  {
    title: "Your content",
    body: (
      <>
        <p>
          You keep ownership of what you upload. By uploading, you confirm you
          have the right to do so and allow AstraMind to process the content
          (extract text, create embeddings, and send passages to the AI
          provider) to answer your questions.
        </p>
        <p>
          Uploaded documents are visible to all users of this deployment. Do not
          upload confidential, personal, or sensitive material.
        </p>
      </>
    ),
  },
  {
    title: "Acceptable use",
    body: (
      <>
        <p>You agree not to:</p>
        <ul className="list-disc space-y-1 pl-5">
          <li>
            Upload content that is illegal or that you do not have the right to
            share
          </li>
          <li>
            Upload malicious files or try to disrupt or overload the service
          </li>
          <li>Use automated tools to send large volumes of requests</li>
          <li>Try to access, change, or delete data you did not upload</li>
        </ul>
      </>
    ),
  },
  {
    title: "AI answers can be wrong",
    body: (
      <p>
        Answers are generated by an AI model from passages found in your
        documents. They can be incomplete or incorrect. Check important
        information against the original document, and do not rely on answers
        for legal, medical, or financial decisions.
      </p>
    ),
  },
  {
    title: "Removal of content",
    body: (
      <p>
        Anyone can delete uploaded files from the Upload page. We may also
        remove files or limit access at any time, for example to protect the
        service or the quota it depends on.
      </p>
    ),
  },
  {
    title: "No warranty",
    body: (
      <p>
        AstraMind is provided as is and as available, without warranties of any
        kind, including accuracy, availability, or fitness for a particular
        purpose.
      </p>
    ),
  },
  {
    title: "Limitation of liability",
    body: (
      <p>
        To the extent allowed by law, the author is not liable for any loss or
        damage arising from your use of AstraMind, including lost data or
        decisions made from AI answers.
      </p>
    ),
  },
  {
    title: "Changes",
    body: (
      <p>
        We may update these terms. Continued use after a change means you accept
        the new version.
      </p>
    ),
  },
  {
    title: "Contact",
    body: (
      <p>
        Questions about these terms? Open an issue on{" "}
        <a
          href="https://github.com/sanju1098/rag-chatbot/issues"
          target="_blank"
          rel="noopener noreferrer"
          className="font-medium text-foreground underline underline-offset-4"
        >
          GitHub
        </a>
        .
      </p>
    ),
  },
];

export default function TermsPage() {
  return (
    <div className="container mx-auto px-4 py-10 sm:px-6 md:py-14 lg:px-8">
      <div className="mx-auto max-w-3xl space-y-8">
        <div>
          <h1 className="text-3xl font-semibold tracking-tight md:text-4xl">
            Terms of Use
          </h1>
          <p className="mt-3 text-base text-muted-foreground md:text-lg">
            The rules for using AstraMind.
          </p>
          <p className="mt-2 font-mono text-xs text-muted-foreground">
            Last updated: 8 October 2026
          </p>
        </div>

        <div className="divide-y rounded-xl border bg-card shadow-sm">
          {sections.map((s) => (
            <section key={s.title} className="space-y-2 p-4 sm:p-5">
              <h2 className="text-base font-medium">{s.title}</h2>
              <div className="space-y-3 text-sm leading-relaxed text-muted-foreground">
                {s.body}
              </div>
            </section>
          ))}
        </div>
      </div>
    </div>
  );
}
